const express = require('express');
const router = express.Router();
const upload = require('../middleware/uploadMiddleware');
const { protect } = require('../middleware/authMiddleware');

/**
 * @desc    Upload an image to Cloudinary
 * @route   POST /api/upload
 * @access  Private (Admin Only)
 */
// 'image' is the exact form-data key the frontend must use
router.post('/', protect, upload.single('image'), (req, res, next) => {
  try {
    if (!req.file) {
      res.status(400);
      throw new Error('No image file provided in the payload.');
    }

    // req.file.path contains the live URL generated by Cloudinary
    res.status(200).json({
      success: true,
      message: 'Image successfully uploaded to CDN.',
      imageUrl: req.file.path 
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;